server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: uaa-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/inc?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
## actuator
management:
  endpoints:
    web.exposure.include: "*"
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG